### PR TITLE
Added dynamic plex download URLs

### PR DESCRIPTION
**Pull request by zackbcom**

### CODE REVIEW

**Comment by chrisanthropic** [comment]
Out of curiosity, what does adding the plex token to the end of the request do? Does it use that as the token?

**Comment by zackbcom** [comment]
I believe it gives access to the "Plex Pass" downloads. I was testing it, but it seems that they are currently both on the same version.

**Comment by chrisanthropic** [comment]
Ok, cool. Thanks for the help!

**Comment by zackbcom** [comment]
Found this explanation on another git. Set "X-Plex-Token" to the auth token, if no token is specified or it is invalid, the list will return public downloads by default

Source: https://github.com/mrworf/plexupdate/blob/master/plexupdate.sh

**Pull request merged**
